### ISSUE TITLE
"choice_id" not found

### ISSUE THREAD

**Issue by aiccu** [tntp/surveymonkey#46]
Error in ~!is.na(choice_id) : object 'choice_id' not found
In addition: Warning messages:
1: Unknown or uninitialised column: 'choice_id'. 
2: Trying to compute distinct() for variables not found in the data:
- `choice_id`, `choice_position`
This is an error, but only a warning is raised for compatibility reasons.
The following variables will be used:
- q_unique_id
- question_id
- choice_text 
Called from: ~!is.na(choice_id)
attr(,"class")
[1] "quosure" "formula"
attr(,".Environment")
<environment: 0x7ffbc6b0be00>
B

**Comment by sfirke** [comment]
Thanks for posting your error message!  I was able to recreate your error message by creating a survey with only simple question types.  I have now pushed a commit that, at least for me, has addressed this.  I'll close this issue, but please let me know if it persists after reinstalling the latest with `devtools::install_github("tntp/surveymonkey")`.

**Comment by aiccu** [comment]
Fantastic - this package will really streamline our workflow (in addition to your excellent Janitor package). Thanks a ton!

**Comment by sfirke** [comment]
Excellent.  I'll reopen this as I should fix that warning too.  Note to self, I think that involves moving the fix at https://github.com/tntp/surveymonkey/blob/master/R/assemble.R#L93 (and line 95) up to where `x` is created by the join at line 23.  It's great to see this package getting used! 😄
