### ISSUE TITLE
Remove HTML Tags When Importing from Questions

### ISSUE THREAD

**Issue by aiccu** [tntp/surveymonkey#47]
**Minor feature enhancement request:** imports HTML-markup tags to colname when present (see image) 

![image](https://user-images.githubusercontent.com/56412165/69079675-61bf9280-09ef-11ea-8ea0-e9bc4e943c51.png)

 -label:enhancement.

**Comment by sfirke** [comment]
agreed that this is important!  I have an issue open already for this and will close this to consolidate the discussion there: https://github.com/tntp/surveymonkey/issues/13

**Comment by sfirke** [comment]
@aiccu FYI this just got implemented as `strip_html()`, if you still need this give it a shot and see what you think!
