### ISSUE TITLE
Add support for file upload question type

### ISSUE THREAD

**Issue by sfirke** [tntp/surveymonkey#56]
At least check what the API returns for that.  A URL?

**Comment by mattroumaya** [comment]
We use this for internal intake forms for survey requests:

`content_type` and `download_url` are returned from the API and named as such, `attachment` will be the "question" for the document upload. 

![image](https://user-images.githubusercontent.com/40671730/106490712-17a3bf00-6484-11eb-9acf-502e03bcb577.png)
