### ISSUE TITLE
Pull responses from web link collectors in addition to the email collector

### ISSUE THREAD

**Issue by crosscr** [tntp/surveymonkey#59]
Hey Sam,

Using this package for a survey I'm working on. Most of my survey responses came from an email collector, but I have a few respondents that required their own web link collectors. I ran into a problem where the responses from the web link collectors aren't being pulled in. When I used this on a different survey back in February, it pulled in all responses (I tested that code and it's not pulling the web collector responses now), so I'm not sure why it isn't anymore.

There's no rush on this, but just flagging.

Thanks,
Cassandra

**Comment by sfirke** [comment]
Doh, I will check that out - though not sure when given my schedule.  Can you email me the survey ID number where you're seeing this behavior so I can work with it as an example?

**Comment by sfirke** [comment]
Confirmed that this was resolved by updating to the latest packages
