### ISSUE TITLE
Pull tag data

### ISSUE THREAD

**Issue by shamahutoto** [tntp/surveymonkey#61]
Hi,

I’ve been using your package to download responses and then manually going back into SurveyMonkey to count up the tagged responses in the text field answer.

Is there a way that a function could be made to download these tags automatically?

I reached out to SurveyMonkey and they say this has been written into the api. If you search “SurveyMonkey test” here it shows where the data can be found https://jsonblob.com/bed1d46c-e5f2-11ea-b735-09a5984821f9

**Comment by sfirke** [comment]
Thanks for the JSON blob.  Do you know what question type this is, on the design side?  For further investigation, I'd probably make a survey myself with the question type to explore it myself.

**Comment by shamahutoto** [comment]
Hi Sam,

I'm not sure about this specific example but I originally asked them about
the "other" comment box tags you can add at the end of multiple choice
questions.

Thanks for looking into it

**Comment by shamahutoto** [comment]
https://imgur.com/XS7JddE

Here's an example of where tags are inputted on SurveyMonkey

**Comment by sfirke** [comment]
That screenshot is great, thanks!  I'd never noticed the "tags" there.

**Comment by mattroumaya** [comment]
@shamahutoto closing for now but feel free to reopen if needed.
