### ISSUE TITLE
Duplicate Records seemingly based on required questions

### ISSUE THREAD

**Issue by dshipley2** [tntp/surveymonkey#62]
Hey Sam/Dustin,

I'm using the surveymonkey package on a project I'm supporting a local nonprofit on. Obviously opting for this package and the API connection vs. manual download and upload to R since questions/columns are a lot cleaner this way. The issue I'm having is that when I pull data down using this package, it's creating duplicate records for respondents. There's additional columns added to the data being pulled that I haven't encountered before (type and required). When I follow where the records that should be 1 are splitting it's based on a question at the end of the survey asking respondents to provide their email addresses. On those records the type field = email and the required field = FALSE. I don't know why these two addition fields are being pulled in, but am wondering if they weren't would that prevent the responses from being broken into 2 separate records, one of which only having the email address at the end.

I'll probably do a workaround where I drop the email question because I don't need it for analysis and replace the values of type and required with NULL. And then I can drop the records that have no responses.

Thanks!
Danica

**Comment by sfirke** [comment]
Thanks for filing this bug report!  I don't think I could diagnose and fix it without access to the survey itself, to poke at it, but this is still good to have in case it comes up for other users and/or on a survey I do have access to.

**Comment by sfirke** [comment]
closed by #68 - I think.  If not, this can be reopened.
