### ISSUE TITLE
parse_survey parameters are too limited

### ISSUE THREAD

**Issue by krystian8207** [tntp/surveymonkey#63]
First of all, thank you for the great package, this makes my life much easier :)

Coming back to my issue, it is related to `parse_survey` function.
In order to optimize the number of requests, I save historical data externally and source only the latest responses.

Whereas `get_responses` (used inside of `parse_survey`) offers a lot of additional parameters that allow to restrict the request, `parse_survey` does not.
Are there any contradictions to extend `parse_survey` parameters? 
Adding a simple ellipsis (`...`) parameter that is passed to inner `get_responses` would solve it quickly.

**Comment by sfirke** [comment]
Great suggestion.  Take a look at #64, do you think that does it?  Anything you'd add or change?

**Comment by krystian8207** [comment]
Thank you for your quick response and PR. This is definitely what I needed.
There are some CI errors, but I expect related to CI setup and not the change itself.

I've started to use the package a few days ago. Anything new I find out, I'll definitely cover in new issues or own PRs.

**Comment by sfirke** [comment]
CI with R packages is vexing me right now, I have two different packages with CI failures that appear unrelated to the actual code 😩 

I'll merge it.  Thanks for the suggestion!
