### ISSUE TITLE
parse_survey not working & sm_login() does not exist?

### ISSUE THREAD

**Issue by wnfaulkner** [tntp/surveymonkey#75]
Hello, 

First, while I am a regular [R] user and have created my own packages, I am not as experienced with GitHub & issues, so I apologize if my comments miss the mark in any way. I am attempting to get set up using this package to connect directly to a client's data. I have their surveymonkey login info. 

I have followed the Usage directions in the package ReadMe. Everything has worked up to parsing the survey into a data.frame (see screenshot). 

- getOption("sm_oath_token") works correctly. Note, however, that under 'Add your OAuth token to your .Rprofile' the ReadMe file specifies getOption("sm_oauth_token"), which does not work - including the 'u' results in NULL output.
- fetch_survey_obj() appears to work correctly when the oauth_token parameter is specified using getOption.
- parse_survey(), however, throws an error saying that the oauth_token must be specified. 
- smlogin() command appears not to exist.

Any help you can provide would be much appreciated!

![surveymonkey parse_survey error screenshot](https://user-images.githubusercontent.com/13836656/139767397-e3b0b8a1-3fa0-46fb-ad72-0ce5a0cd3d48.PNG)

**Comment by mattroumaya** [comment]
Hi @wnfaulkner, 

You shouldn't have to specify `oauth_token` for each call. 

If you run `usethis::edit_r_profile()` in your console, your .Rprofile will pop up, and you can save the following:

`options(sm_oauth_token = "YOUR_ACTUAL_OAUTH_TOKEN")`

After saving the oauth token in your .Rprofile, you'll need to restart RStudio. This will allow the default arg `oauth_token = getOption("sm_oauth_token")` to work properly.

Then, you should be able to run the code you have above:

```
survey1.df <-
  308494268 %>%
  fetch_survey_obj() %>%
  parse_survey()
```

**Comment by wnfaulkner** [comment]
Hello @mattroumaya,

Thank you so much for your reply! 

I had followed those steps, but your reply helped me to check more thoroughly and I noticed that I had incorrectly specified `options(sm_oath_token = "TOKEN")` in my .rprofile file (as opposed to sm_oauth_token). Hence, my original note about the ReadMe was my own mistake. Once I fixed that, saved, and restarted R I no longer got the error.

I am now, unfortunately, dissecting a new error that parse_survey() is throwing, but I'm going to try to be as thorough with my diagnosis as possible to try to not waste your time. 

Once again, thanks for the assistance!

**Comment by mattroumaya** [comment]
Thanks @wnfaulkner! Feel free to open an issue if you're running into something with `parse_survey()`. I've personally had a few issues with less common question types that might not be supported (yet!). 

I'm going to close this one out, but again, feel free to create another thread if you run into any issues.
