### ISSUE TITLE
Column (Date Modified) Showing Results That Differ From Direct Export From Survey Monkey

### ISSUE THREAD

**Issue by de3ert** [tntp/surveymonkey#82]
When viewing individual responses in SurveyMonkey, I notice that some records show a "Last Modified" date that differs from the date under "date_modified" that is created by the package.  Do you have any idea why the difference is occurring? Thank you!

**Comment by mattroumaya** [comment]
Can you provide a little more info? Where does `Last Modified` come from, and where does `date_modified` come from?

**Comment by de3ert** [comment]
In SurveyMonkey, after selecting my survey I navigate to Analyze Results and then to Individual Responses to find the Last Modified date of each respondent. The Last Modified date also exports from SurveyMonkey as End Date. In R, after I run 
 
`survey_df <- [survey id] %>%
  fetch_survey_obj %>%
  parse_survey`

I then take a look at column names and see the `date_modified` column. Most of the values match Last Modified/End Date, but not all match.

**Comment by mattroumaya** [comment]
I plan to look into this further soon but haven't had the time. Have you found any additional info about this issue @de3ert?

**Comment by mattroumaya** [comment]
@de3ert closing for now but feel free to reopen if needed.
