### ISSUE TITLE
Authentication when deploying to RStudio Connect

### ISSUE THREAD

**Issue by paulditterline** [tntp/surveymonkey#86]
Hello-

I'm using `flexdashboard` to show metrics, some of which come from Survey Monkey. I was hoping to use this package to make the data live from Survey Monkey.

My application works locally by referencing the oauth_token in `fetch_survey_object()` as shown below:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/10035027/145075458-10d0c969-5be5-47d4-8ed6-e2b3ded8066b.png">

However, when I deploy and add this variable to the app in RStudio Connect:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/10035027/145075539-7cd0243a-8212-42b1-8db2-d9195e02bd87.png">

The app fails, and I see the following error message in the logs:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/10035027/145075626-22e9158f-b6fa-4371-b422-1530c25fb03f.png">

Oddly, I don't see an `smlogin()` function available from the package. 

I saw the readme was updated with some information about authentication, so I'm guessing this has been changed recently. Any thoughts on authentication for deployed applications using this package?

Thanks!

**Comment by paulditterline** [comment]
Turns out the error was coming from `parse_survey()`, and when I put the same argument in that function for the token, it worked when deployed!

**Comment by mattroumaya** [comment]
@paulditterline glad to hear it's working! I'm definitely interested in learning more about RStudio Connect, but don't currently use it at my job.

**Comment by sfirke** [comment]
FWIW I believe `smlogin` was a function left over from the version of this package developed years ago by Thomas Leeper, for the v2 API (SurveyMonkey is now on v3).  That may have been a bit I left in, intending to update but not finishing it?  At any rate I don't think `smlogin` is relevant anymore.

**Comment by mattroumaya** [comment]
Thanks for the background info, @sfirke! 

A few people have encountered the `smlogin()` error recently, so I'm going to update it and instead direct to the `sm_oauth_token` documentation.
