### ISSUE TITLE
API access for paid plans

### ISSUE THREAD

**Issue by humoroussmile** [tntp/surveymonkey#96]
Hello! Thank you for this spectacular package. I've been using this with great success up until recently when I started receiving 403 errors. I'm not exactly sure what the issue is. Our app's scopes are set to "Required" as listed in the README.md.

Per your README.md, "This is confirmed to work for paid plans at the Advantage and Premier levels. Unconfirmed if standard & basic (free) plans are granted sufficient API access." One consideration is that this may not in fact work for Advantage plans any longer. While our paid plan has not changed, [SurveyMonkey's list of plans](https://www.surveymonkey.com/pricing/?ut_source=dev_portal) only lists API access for Premier and Enterprise plans. That being said, [various scopes](https://developer.surveymonkey.com/api/v3/#scopes) claim on their site not to require a paid SurveyMonkey account.

I just wanted to confirm if the scope settings for "not requested" are correct, and if there is an update on whether your package still works for the paid Advantage level plan. Thanks!

**Comment by mattroumaya** [comment]
Hi @humoroussmile - this does seem like an account/API access issue. I would check in with a SurveyMonkey rep and see if your account is eligible to use the API as a first step. If you are supposed to have access, then I'd suggest reporting back and we can walk through some troubleshooting.

**Comment by humoroussmile** [comment]
Thank you for your quick response @mattroumaya! I reached out to SurveyMonkey, and their response was very helpful, so I hope this helps for the purposes of your tool and for other users:

**Survey Monkey Technical Support**: "The Team Advantage [plan] does not include direct API access as a feature... direct API access is only available on our Premier or Enterprise plan... On any of our plans... you can create a draft app, which will work for 90 days... However, unless the draft app gets deployed, which requires the direct API access feature, it will stop working after the 90-day draft period."

The response from SurveyMonkey explains why your package was working for my team for several months up until recently. Thanks again for your contributions!

**Comment by mattroumaya** [comment]
@humoroussmile Thank you for the detailed response! It's helpful to know what's going on with SurveyMonkey's enterprise plans. I'll close this out for now, since it seems like you've found a workaround/resolution.
